apiVersion: v1
kind: Secret
metadata: 
    name: netscaler-secrets
data: 
  NETSCALER_HOST:  {{ .Values.netscaler.host | b64enc | quote }}
  NETSCALER_USERNAME:  {{ .Values.netscaler.username | b64enc | quote }}
  NETSCALER_PASSWORD:  {{ .Values.netscaler.password | b64enc | quote }}
  NETSCALER_SVC_GRP:  {{ .Values.netscaler.servicegroup | b64enc | quote }}