#
# 
#

netscaler:
  host: http://localhost:32768
  username: abcdef
  password: defghi
  servicegroup: abcd

replicaCount: 1

image:
  repository: ghcr.io/matrixmind-cloud/netscaler-endpoint-controller
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources: 
  requests:
    cpu: 20m
    memory: 24Mi
  limits:
    cpu: 100m
    memory: 48Mi 

nodeSelector: 
  node-role.kubernetes.io/controlplane: "true"

tolerations: 
- effect: NoSchedule
  key: node-role.kubernetes.io/controlplane
  operator: Equal
  value: "true"
- effect: NoExecute
  key: node-role.kubernetes.io/etcd
  operator: Equal
  value: "true"

affinity: {}
