name: 'build'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/matrixmind-cloud/netscaler-endpoint-controller:latest
          push: true
